### ISSUE TITLE
我的.env沒什麼反應

### ISSUE THREAD

**Issue by brain00021** [clarencetw/line-bot#1]
我今天練習第四堂的時候 本來想要依照it幫幫忙的文章操作.env的設定
如下
`CHANNEL_SECRET=59c59c0c9d230c7e0e45dd4d968bcbe1
CHANNEL_ACCESS_TOKEN=Vq1EY+xAoKUca1GmvJNJdlzPiSqaLR+1asfXx01/K2QnCkx+Uh0xKMxf/CI1DDUN9IfkOz0AwoEmSqqAgevWWVO0Mh+9d/nyrorhZNObGrX4oRfu98kH72kSg4OwiHYoNTFyGl/np7btNecEoe/IrgdB04t89/1O/w1cDnyilFU=
BASE_URL=https://d837f4b8.ngrok.io:3000
RICHMENUID_DEFAULT=richmenu-e97b71914d6ffffffffac0da43445966
RICHMENUID_CONTROLLER=richmenu-e97b71914d6ffffffffac0da43445966
`
後來要npm start的時候她忽然說 需要channelID
所以我在裡面搜尋了一下找到了好像需要以下的東西 所以我也補上了.env裡面
`
LINE_LOGIN_CHANNEL_ID=1653513726
LINE_LOGIN_CHANNEL_SECRET=59c59c0c9d230c7e0e45dd4d968bcbe1
LINE_LOGIN_CALLBACK_URL=https://d837f4b8.ngrok.io:3000
`
結果我的npm start log 在那邊一動也不動了...求解

**Comment by brain00021** [comment]
附上我的操作狀況希望你能更了解一下 :D
https://imgur.com/a/M7krhDd

**Comment by clarencetw** [comment]
這樣子就是 Server 開起來了，現在應該可以用 http://localhost:3000/ 看有 Web 就是代表正常
LINE_LOGIN 是因為後面的章節需要，我忘記切 tag 了，過幾天有空我加一下 tag，應該會比較好做練習

**Comment by clarencetw** [comment]
另外如果是第四堂課程歡迎先看這個  [Commit](https://github.com/clarencetw/line-bot/tree/fde20e86a92649a4f2c86dbed6846cac46eeaaf7) 應該可以幫到你，有問題歡迎再開啟 Issues！
